language: python
python:
  - "2.6"
  - "2.7"
addons:
  apt:
    packages:
sudo: false
install: true
matrix:
  include:
    python: 2.6
    install: true
      - pip install pytest
      - pip install pytest-cov
      - pip install mock
script:
  - python -m pytest tests
