language: python
sudo: false
matrix:
  include:
    python: 2.6
    install:
      - pip install pytest
      - pip install pytest-cov
      - pip install mock
    script: python -m pytest tests
    python:
      - "2.7"
      - "3.5"
    addons:
      apt:
        packages:
    install: true
    script:
      - python setup.py test
